### ISSUE TITLE
Citus

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#3]
Every single issue should have the following

- [x] Precise steps on how to add the extension to the Dockerfile
- [x] How to enable the extension
- [x] Actual smoke tests described in English
- [x] CI Updated with smoke tests

**Comment by jayanth-kumar-morem** [comment]
Hi @ChakshuGautam , I would like to take this one up, can you assign me to this

**Comment by jayanth-kumar-morem** [comment]
Thanks @ChakshuGautam ,
I have raised a PR #11

**Comment by ChakshuGautam** [comment]
Hey @jayanth-kumar-morem currently Citus and Timescale are not compatible - "Another time-partitioning extension for PostgreSQL is TimescaleDB. Unfortunately, Citus and TimescaleDB are currently not compatible." from [this article](https://www.citusdata.com/blog/2021/10/22/how-to-scale-postgres-for-time-series-data-with-citus/). Can you also add a feature to disable TimescaleDB by default so the user has a choice to add it when needed?

Also added a checklist for this ticket. Please update the smoke tests for this addition. Thanks :)

**Comment by jayanth-kumar-morem** [comment]
Hi @ChakshuGautam ,

Could you share more details on the last point in the checklist, `Build pipeline updates needed` .

To provide users with the option to enable or disable TimescaleDB by default, we can make use of an environment variable to control the extension creation during the PostgreSQL initialization process. We can edit the entrypoint script for the Docker image that checks the environment variable and enables TimescaleDB accordingly. Can you confirm whether we are on the same plate on implementing this, so that I can go ahead with the coding part :)

**Comment by ChakshuGautam** [comment]
Hey, @jayanth-kumar-morem the PR looks good. I have removed the `Build pipeline updates needed` from the checklist. I will add it as a separate ticket.

**Comment by jayanth-kumar-morem** [comment]
Okay @ChakshuGautam , is there anything else we need to work on this issue before merging the code. ?
