### ISSUE TITLE
HyperLogLog

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/WarpSQL#9]

**Comment by Manas23601** [comment]
Can I work on this?

**Comment by Manas23601** [comment]
@PiyushRaj927 Have you already solved the issue?

**Comment by PiyushRaj927** [comment]
Hi @Manas23601, I wanted to let you know that I successfully resolved the issue last week, but unfortunately, I couldn't complete my PR draft due to unforeseen circumstances. I apologize for any inconvenience caused by my miscommunication. In the meantime, would it be possible for you to handle #10? Thank you.
